module Page.Common exposing (..)
import Browser exposing (..)
import Html.Events exposing(..)
import Html.Attributes exposing(..)
import Session exposing(..)
import Html exposing (..)
import Route exposing(..)


commonHeader : String -> String -> Html msg
commonHeader icon title =
    div [ class "titlewrap" ]
        [ div [ class "columns" ]
            [ div [ class "column is-half pagename" ]
                [ div [ class "yficon" ]
                    [ img [ src icon , alt "icon" ]
                        []
                    ]
                , div [ class "yftext" ]
                    [ strong []
                        [ text title ]
                    ]
                ]
            , div [ class "column is-half" ]
                [ div [ class "field is-grouped" ]
                    [ p [ class "control is-expanded" ]
                        [ input [ class "input", type_ "text", placeholder "운동을 검색하세요" ]
                            []
                        ]
                    , p [ class "control yf_con" ]
                        [ a [ class "button is-info yf_searchwindow" ]
                            [ text "검색" ]
                        ]
                    ]
                ]
            ]
        ]

commonHeader2 : String -> String -> Html msg
commonHeader2 icon title =
    div [ class "titlewrap" ]
        [ div [ class "columns" ]
            [ div [ class "column is-full pagename" ]
                [ div [ class "yficon" ]
                    [ img [ src icon , alt "icon" ]
                        []
                    ]
                , div [ class "yftext" ]
                    [ strong []
                        [ text title ]
                    ]
                ]

            ]
        ]
commonJustHeader : String -> String -> Html msg        
commonJustHeader icon title =
       div [ class "titlewrap" ]
        [ div [ class "columns" ]
            [ div [ class "column is-full pagename" ]
                [ div [ class "yficon" ]
                    [ img [  src icon, alt "icon" ]
                        []
                    ]
                , div [ class "yftext" ]
                    [ strong []
                        [ text title ]
                    ]
                ]
            ]
        ]

myPageCommonHeader scrRight scrLeft= 
    div [ class "submenu" ]
        [  
            i [ class "fas fa-caret-left scrStyle", onClick scrLeft ]
            [] ,
            div [ class "haderIconWrap", id "scrollCtr" ]
            [ a [ class "headerIcons" , Route.href Route.MyC]
                [ img [ src "../image/icon_calendar.png" ]
                    []
                , p []
                    [ text "캘린더" ]
                ]
            , a [ class "headerIcons", Route.href Route.MealR]
                [ img [ src "../image/icon_diet.png" ]
                    []
                , p []
                    [ text "식단기록" ]
                ]
            , a [ class "headerIcons", Route.href Route.MyS]
                [ img [ src "../image/icon_stats.png" ]
                    []
                , p []
                    [ text "나의통계" ]
                ]
            , a [ class "headerIcons", Route.href Route.MyScrap]
                [ img [ src "../image/icon_list.png" ]
                    []
                , p []
                    [ text "스크랩리스트" ]
                ]
            , a [ class "headerIcons", Route.href Route.MyPost]
                [ img [ src "../image/icon_management.png" ]
                    []
                , p []
                    [ text "내 게시물관리" ]
                ]
            , a [ class "headerIcons", Route.href Route.Info]
                [ img [ src "../image/icon_notice.png" ]
                    []
                , p []
                    [ text "공지사항" ]
                ]
            , a [ class "headerIcons", Route.href Route.Faq]
                [ img [ src "../image/icon_qna.png" ]
                    []
                , p []
                    [ text "1:1문의" ]
                ]
            ],
            i [ class "fas fa-caret-right scrStyle", onClick scrRight ]
            [] 
        ]

appHeaderSearch title style= 
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn" ]
            []
        , div [ class "m_yf_topboxtitle" ]
            [ text title ]
        , div [ class "m_nextbtn" ]
            [ i [ class "fas fa-search" ]
                []
            ]
        ]

appHeadermypage title style= 
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn" ]
            []
        , div [ class "m_yf_topboxtitle" ]
            [ text title ]
        , div [ class "m_nextbtn" ]
              [ ]
            ]
        

appHeaderDetail title style back=
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn", onClick back]
            [ i [ class "fas fa-times" ]
                []
            ]
        , div [ class "m_topboxtitle" ]
            [ text title ]
        ]

appHeaderback title style back=
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn" , onClick back]
            [ i [ class "fas fa-angle-left" ]
                []
            ]
        , div [ class "m_topboxback" ]
            [ text title]
        , div [ class "m_nextbtn" ]
            []
        ]


appHeaderBDetail title style back=
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn", onClick back]
            [ i [ class "fas fa-angle-left" ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text title ]

        ]
appHeaderBothBtn title style back icon btnText go=
    div [ class ("commonHeader " ++ style) ]
        [ a [ class "m_backbtn", Route.href back ]
            [ i [ class icon ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text title ]
        , a [ class "m2_nextbtn", Route.href go ]
            [ text btnText ]
        ] 

appHeaderBothfnq title style back icon btnText go=
    div [ class ("commonHeader " ++ style) ]
        [ a [ class "m_backbtn", Route.href back ]
            [ i [ class icon ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text title ]
        , a [ class "m_qna_w_btn", Route.href go ]
            [ text btnText ]
        ] 


appHeaderRDetail title style back icon=
    div [ class ("commonHeader " ++ style) ]
        [ a [ class "m_backbtn", Route.href back]
            [ i [ class icon ]
                []
            ]
        , div [ class "m_topboxtitle" ]
            [ text title ]
 
        ]

appHeaderinforDetail title style back icon=
    div [ class ("commonHeader " ++ style) ]
        [ a [ class "m_backbtn", Route.href back]
            [ i [ class icon ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text title ]
 
        ]

appHeaderConfirmDetail title style back confirm btnText =
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn", onClick back ]
            [ i [ class "fas fa-times" ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text title ]
        , a [ class "m2_nextbtn", Route.href confirm ]
            [ text btnText ]
        ]

appHeaderConfirmDetailR title style back confirm btnText =
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn", onClick back ]
            [ i [ class "fas fa-times" ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text title ]
        , div [ class "m2_nextbtn", onClick confirm ]
            [ text btnText ]
        ]

appHeaderConfirmDetail2 title style back confirm btnText =
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn", onClick back ]
            [ i [ class "fas fa-angle-left" ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text title ]
        , div [ class "m2_nextbtn", Route.href confirm ]
            [ text btnText ]
        ]



appHeaderBackComplete title style back complete = 
    div [ class ("commonHeader " ++ style) ]
        [ div [ class "m_backbtn" , onClick back]
            [ i [ class "fas fa-angle-left" ]
                []
            ]
        , div [ class "m3_topboxtitle" ]
            [ text "운동추가" ]
        , div [ class "m_nextbtn", onClick complete ]
            [ text "완료" ]
        ]


spinner = 
    div [ class "sk-fading-circle" ]
        [ div [ class "sk-circle1 sk-circle" ]
            []
        , div [ class "sk-circle2 sk-circle" ]
            []
        , div [ class "sk-circle3 sk-circle" ]
            []
        , div [ class "sk-circle4 sk-circle" ]
            []
        , div [ class "sk-circle5 sk-circle" ]
            []
        , div [ class "sk-circle6 sk-circle" ]
            []
        , div [ class "sk-circle7 sk-circle" ]
            []
        , div [ class "sk-circle8 sk-circle" ]
            []
        , div [ class "sk-circle9 sk-circle" ]
            []
        , div [ class "sk-circle10 sk-circle" ]
            []
        , div [ class "sk-circle11 sk-circle" ]
            []
        , div [ class "sk-circle12 sk-circle" ]
            []
        ]

